Fix test failure
For unknown reasons, the testing call (used by all the infer_intent tests) started giving an error:
```
infer_intent::tests::infer_binomial' panicked at 'already mutably borrowed: BorrowError', src\speech.rs:1861:38
```

The fix is to first initialize all the rule files (which is way overkill for these tests), but it gets them back to working.